sam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password', views.change_password, name='change_password'),
    #Escalation Details
    path('escadd/', views.esc_upload, name='upload_em'),
    path('escmat/',views.searchesc, name = 'search-em'),
    path('escedit/',views.show1, name = 'search-escedit'),
    path('editesc/<int:id>',views.editesc, name = 'search-edit'),
    path('delete/<int:id>',views.destroy, name = 'search-delete'),
    path('update/<int:id>',views.update, name = 'search-update'),
    #SOP
    path('sops/', views.sop_list, name='sop_list'),
    path('sop_upload/', views.upload_sop, name='upload_sop'),
    path('sopedit/',views.show, name = 'search-sopedit'),
    path('editsop/<int:id>',views.editsop, name = 'search-editsop'),
    path('deletesop/<int:id>',views.destroysop, name = 'search-deletesop'),
    path('updatesop/<int:id>',views.updatesop, name = 'search-updatesop'),
    #training docs
    path('docs/', views.train_doc, name='training_list'),
    path('train_upload/', views.upload_train, name='upload_train'),
    path('train_edit/',views.train_edit, name = 'train_edit'),
    path('deletetrain/<int:id>',views.destroytrain, name = 'deletetrain'),
    #Shift images
    path('roster/', views.shift_img, name='shift_roster'),
    path('shift_upload/', views.upload_shift, name='upload_shift'),
    path('shift_edit/',views.shift_edit, name = 'shift_edit'),
    path('editshift/<int:id>',views.editshift, name = 'search-editshift'),
    path('deleteshift/<int:id>',views.destroyshift, name = 'deleteshift'),
    path('updateshift/<int:id>',views.updateshift, name = 'search-updateshift'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/models.py
from django.db import models

# Create your models here.

#Escalation Matrix
class EscMat(models.Model):
	oper=models.CharField(max_length=100)
	ari=models.CharField(max_length=100)
	aname=models.CharField(max_length=100)
	group_id = models.EmailField()
	person1=models.CharField(max_length=100)
	person2=models.CharField(max_length=100)
	person3=models.CharField(max_length=100)
	person4=models.CharField(max_length=100)
	
	class Meta:
		db_table="escalation"

#SOP		
class sop(models.Model):
	doc = models.CharField(max_length=100, unique=True)
	region = models.CharField(max_length=100)
	operator = models.CharField(max_length=100)
	appt = models.CharField(max_length=100)
	apname = models.CharField(max_length=100)
	topic = models.CharField(max_length=100)
	ip = models.CharField(max_length=100)
	pdf = models.FileField(upload_to='static/pdf/sop')
	
	def __str__(self):
		return self.title
	def delete(self, *args, **kwargs):
		self.pdf.delete()
		super().delete(*args, **kwargs)
	class Meta:
		db_table = "sop"

#Training Documents
class train(models.Model):
	doc = models.CharField(max_length=100, unique=True)
	product = models.CharField(max_length=100)
	pdf = models.FileField(upload_to='static/pdf/training')
	
	def __str__(self):
		return self.title
	def delete(self, *args, **kwargs):
		self.pdf.delete()
		super().delete(*args, **kwargs)
	class Meta:
		db_table = "train"

#Shift Roster
class shift(models.Model):
	year = models.CharField(max_length=4)
	month = models.CharField(max_length=12)
	level = models.CharField(max_length=5)
	imag = models.FileField(upload_to='static/shift')
	
	def __str__(self):
		return self.title
	def delete(self, *args, **kwargs):
		self.imag.delete()
		super().delete(*args, **kwargs)
	class Meta:
		db_table = "shift"

search/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from search.models import *

class EditProfileForm(UserChangeForm):
	password = forms.CharField(label="",  widget=forms.TextInput(attrs={'type':'hidden'}))
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password',)


class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}), )
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
	
	
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

	def __init__(self, *args, **kwargs):
	    super(SignUpForm, self).__init__(*args, **kwargs)

	    self.fields['username'].widget.attrs['class'] = 'form-control'
	    self.fields['username'].widget.attrs['placeholder'] = 'User Name'
	    self.fields['username'].label = ''
	    self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

	    self.fields['password1'].widget.attrs['class'] = 'form-control'
	    self.fields['password1'].widget.attrs['placeholder'] = 'Password'
	    self.fields['password1'].label = ''
	    self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

	    self.fields['password2'].widget.attrs['class'] = 'form-control'
	    self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
	    self.fields['password2'].label = ''
	    self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

class esc_form(forms.ModelForm):
	class Meta:
		model = EscMat
		fields = "__all__"

class sop_form(forms.ModelForm):
	class Meta:
		model = sop
		fields = "__all__"
				
class train_form(forms.ModelForm):
	class Meta:
		model = train
		fields = "__all__"	

class shift_form(forms.ModelForm):
	class Meta:
		model = shift
		fields = "__all__"  

search/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib import messages 
from .forms import SignUpForm, EditProfileForm
from search.models import *
from search.forms import *

@cache_control(no_cache=True, must_revalidate=True, no_store=True)

# Create your views here.

def home(request):
	return render(request, 'search/home.html', {})

#Shift Roster Module
#Viewing image
def shift_img(request):
	if request.method=="POST":
		month=request.POST.get('month')
		year=request.POST.get('year')
		level=request.POST.get('level')
		month=month+'%'
		shift_search=shift.objects.raw('select * from shift where year="'+year+'"and level="'+level+'" and month like "'+month+'"')
		return render(request,'search/shift.html',{"shift":shift_search})
	else:
		shift_obj=shift.objects.raw('select * from shift ORDER BY ID DESC LIMIT 4')
		return render(request,'search/shift.html',{"shift":shift_obj})


def shift_edit(request):
	if request.method=="POST":
		month=request.POST.get('month')
		year=request.POST.get('year')
		level=request.POST.get('level')
		month=month+'%'
		shift_search=shift.objects.raw('select * from shift where year="'+year+'"and level="'+level+'" and month like "'+month+'"')
		return render(request,'search/shift_edit.html',{"shift":shift_search})
	else:
		shift_obj=shift.objects.raw('select * from shift')
		return render(request,'search/shift_edit.html',{"shift":shift_obj})

def upload_shift(request):
	if request.method == "POST":
		form = shift_form(request.POST, request.FILES)
		if form.is_valid():
			try:
				form.save()
				messages.success(request, ('Uploaded successfully...!'))
				return redirect('/shift_upload')
			except:
				pass
	else:
		form = shift_form()
	return render(request,"search/upload_shift.html",{'form':form})

def editshift(request,id):
	shift_det = shift.objects.get(id=id)
	return render(request,'search/edit_shift.html',{'shift':shift_det})
	
def updateshift(request,id):
	shift_det = shift.objects.get(id=id)
	form = shift_form(request.POST, request.FILES, instance = shift_det)
	if form.is_valid():
		form.save()
		messages.success(request, ('Updated successfully...!'))
		return redirect('/shift_edit')
	return render(request,'search/edit_shift.html',{'shift':shift_det})

def destroyshift(request,id):
	shift_det = shift.objects.get(id=id)
	shift_det.delete()
	return redirect("/shift_edit")
	
#Training documents Module
#Viewing Document
def train_doc(request):
	docs=train.objects.all()
	return render(request, 'search/train.html', {'train': docs})

def train_edit(request):
	docs=train.objects.all()
	return render(request, 'search/trainedit.html', {'train': docs})

def upload_train(request):
	if request.method == "POST":
		form = train_form(request.POST, request.FILES)
		if form.is_valid():
			try:
				form.save()
				messages.success(request, ('Uploaded successfully...!'))
				return redirect('/train_upload')
			except:
				pass
	else:
		form = train_form()
	return render(request,"search/upload_train.html",{'form':form})

def destroytrain(request,id):
	train_det = train.objects.get(id=id)
	train_det.delete()
	return redirect("/train_edit")
	
#SOP Module
#Searching SOP
def sop_list(request):
	if request.method=="POST":
		region=request.POST.get('region')
		operator=request.POST.get('operator')
		topic=request.POST.get('topic')
		operator=operator+'%'
		topic=topic+'%'
		sop_search=sop.objects.raw('select * from sop where (operator like "'+operator+'" or operator = "Common") and topic like "'+topic+'" and (region= "'+region+'" or region = "Common") order by doc ASC')
		return render(request,'search/sop.html',{"sop":sop_search})
	else:
		sopobj=sop.objects.raw('select * from sop order by doc ASC')
		return render(request,'search/sop.html',{"sop":sopobj})

def show(request):
	if request.method=="POST":
		region=request.POST.get('region')
		operator=request.POST.get('operator')
		topic=request.POST.get('topic')
		operator=operator+'%'
		topic=topic+'%'
		sop_search=sop.objects.raw('select * from sop where (operator like "'+operator+'" or operator = "Common") and topic like "'+topic+'" and (region= "'+region+'" or region = "Common") order by doc ASC')
		return render(request,'search/sopedit.html',{"sop":sop_search})
	else:
		sopobj=sop.objects.raw('select * from sop order by doc ASC')
		return render(request,'search/sopedit.html',{"sop":sopobj})

#Upload SOP		
def upload_sop(request):
	if request.method == "POST":
		form = sop_form(request.POST, request.FILES)
		if form.is_valid():
			try:
				form.save()
				messages.success(request, ('Uploaded successfully...!'))
				return redirect('/sop_upload')
			except:
				pass
	else:
		form = sop_form()
	#return render(request,"search/index.html",{'form':form})
	return render(request,"search/upload_sop.html",{'form':form})

def editsop(request,id):
	sop_det = sop.objects.get(id=id)
	return render(request,'search/editsop.html',{'sop':sop_det})
	
def updatesop(request,id):
	sop_det = sop.objects.get(id=id)
	form = sop_form(request.POST, request.FILES, instance = sop_det)
	if form.is_valid():
		form.save()
		messages.success(request, ('Updated successfully...!'))
		return redirect('/sopedit')
	return render(request,'search/editsop.html',{'sop':sop_det})
	
def destroysop(request,id):
	sop_det = sop.objects.get(id=id)
	sop_det.delete()
	return redirect("/sopedit")

#Escalation matrix Module	
#Searching EM
def searchesc(request):
	if request.method=="POST":
		oper=request.POST.get('oper')
		app=request.POST.get('ari')
		oper=oper+'%'
		esc_search=EscMat.objects.raw('select * from escalation where oper like "'+oper+'" and ari = "'+app+'"')
		return render(request,'search/escmat.html',{"EscMat":esc_search})
	else:
		escobj=EscMat.objects.raw('select * from escalation')
		return render(request,'search/escmat.html',{"EscMat":escobj})

#editing Module
def show1(request):
	if request.method=="POST":
		oper=request.POST.get('oper')
		app=request.POST.get('ari')
		oper=oper+'%'
		esc_search=EscMat.objects.raw('select * from escalation where oper like "'+oper+'" and ari = "'+app+'"')
		return render(request,'search/escedit.html',{"EscMat":esc_search})
	else:
		escobj=EscMat.objects.raw('select * from escalation')
		return render(request,'search/escedit.html',{"EscMat":escobj})
	
def editesc(request,id):
	esc_det = EscMat.objects.get(id=id)
	return render(request,'search/editesc.html',{'EscMat':esc_det})
	
def update(request,id):
	esc_det = EscMat.objects.get(id=id)
	form = esc_form(request.POST, instance = esc_det)
	if form.is_valid():
		form.save()
		messages.success(request, ('Updated successfully...!'))
		return redirect('/escedit')
	return render(request,'search/editesc.html',{'EscMat':esc_det})
	
def destroy(request,id):
	esc_det = EscMat.objects.get(id=id)
	esc_det.delete()
	return redirect("/escedit")
	
#Upload Module
def esc_upload(request):
	if request.method == "POST":
		form = esc_form(request.POST)
		if form.is_valid():
			try:
				form.save()
				messages.success(request, ('Uploaded successfully...!'))
				return redirect('/escadd')
			except:
				pass
	else:
		form = esc_form()
	#return render(request,"search/index.html",{'form':form})
	return render(request,"search/escadd.html",{'form':form})


#Authentication Module
#Login Module

#@login_required(login_url='login')	
def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, ('Logged in successfully...!'))
			return redirect('home')

		else:
			messages.success(request, ('Error Logging In - Please Try Again...'))
			return redirect('login')
	else:
		return render(request, 'search/login.html', {})

def logout_user(request):
	logout(request)
	#messages.success(request, ('You Have Been Logged Out...'))
	return redirect('login')
	
def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			messages.success(request, ('You Have Edited Your Profile...'))
			return redirect('home')
	else:
		form = EditProfileForm(instance=request.user)
	
	context = {'form': form}
	return render(request, 'search/edit_profile.html', context)

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, ('You Have Edited Your Password...'))
			return redirect('home')
	else:
		form = PasswordChangeForm(user=request.user)
	
	context = {'form': form}
	return render(request, 'search/change_password.html', context)
	

        

search/templates/search/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>SAM - Search Engine</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    
    <!--favicon-->
    <link rel="shortcut icon" type="image/png" href="{% static 'logo.png' %}"/>

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        {% if user.is_authenticated %}
        <nav id="sidebar">
            <div class="sidebar-header">
                <center><img src="{% static 'admin.png' %}" alt="admin logo" class="brand-image" width=200px></img>
                <br/><br/><p><b>Search Manager (SAM)</b></p></center>
            </div>

            <ul class="list-unstyled components">
                <center><h5>Welcome<br/>{{ user.first_name }} {{ user.last_name }}</h5></center>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'sop_list' %}">SOP</a>
                </li>
                <li>
                    <a href="{% url 'search-em' %}">Escalation Matrix</a>
                </li>
                <li>
                    <a href="{% url 'training_list' %}">Training Documents</a>
                </li>
                <li>
                    <a href="{% url 'shift_roster' %}">Shift Roster</a>
                </li>
                {% if user.is_superuser or user.is_staff and user.is_authenticated %}
                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Upload</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'upload_sop' %}">SOP</a>
                        </li>
                        <li>
                            <a href="{% url 'upload_em' %}">Escalation Details</a>
                        </li>
                        <li>
                            <a href="{% url 'upload_train' %}">Training Document</a>
                        </li>
                        <li>
                            <a href="{% url 'upload_shift' %}">Shift Roster</a>
                        </li>
                    </ul>
                </li>
                
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Edit/Delete</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'search-sopedit' %}">SOP</a>
                        </li>
                        <li>
                            <a href="{% url 'search-escedit' %}">Escalation Details</a>
                        </li>
                        <li>
                            <a href="{% url 'train_edit' %}">Training Document</a>
                        </li>
                        <li>
                            <a href="{% url 'shift_edit' %}">Shift Roster</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="{% url 'logout' %}" class="download">Log out</a>
                </li>
                <li>
                    <a href="{% url 'change_password' %}" class="download">Change Password</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
       <div id="content">
       <button type="button" id="sidebarCollapse" class="btn btn-info">
       <i class="fas fa-list"></i>
       <span>Toggle Menu</span>
       </button><br/><br/>

{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissable" role="alert">
<button class="close" data-dismiss="alert">
<small><sup>x</sup></small>
</button>
{{ message }}
</div>
{% endfor %}
{% endif %}

{% block content %}
{% endblock %}

{% else %}
<li class="nav-item">
<center><p>Kindly login again to continue ....!!!</p><br/>
<a href="{% url 'login' %}" class="btn btn-danger">Login</a>	
</center>
</li>
{% endif %}

</ul>
</div>
</nav><br/>

<br/>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
    
</body>

</html>

search/templates/search/editesc.html
{% extends "search/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<center>
<div style="border:1px solid pink;padding:20px;font-size:20px">
<h3>Edit Escalation Details</h3>

<form method="POST" class="post-form" action="/update/{{EscMat.id}}">
	{% csrf_token %}

<table class="table table-striped table-bordered table-sm ">
<tr>
<th><center><label>Operator </label></center></th>
<td><center> <input type="text" name="oper" id="id_oper" value="{{ EscMat.oper }}"/> </center></td>
</tr>

<th><center><label for="ari">App or Infra </label></center></th>
<td><center> 
<select name="ari">
<option selected disabled=true>App or Infra</option>
<option value="APP">APP</option>
<option value="INFRA">INFRA</option>
</select></center></td>
</tr>

<tr>
<th><center><label>Application </label></center></th>
<td><center> <input type="text" name="aname" id="id_aname" value="{{ EscMat.aname }}"/> </center></td>
</tr>

<tr>
<th><center><label>Group Mail Id </label></center></th>
<td><center> <input type="text" name="group_id" id="id_group_id" value="{{ EscMat.group_id }}"/> </center></td>
</tr>

<tr>
<th><center><label>Level 1 </label></center></th>
<td><center> <input type="text" name="person1" id="id_person1" value="{{ EscMat.person1 }}"/> </center></td>
</tr>

<tr>
<th><center><label>Level 2 </label></center></th>
<td><center> <input type="text" name="person2" id="id_person2" value="{{ EscMat.person2 }}"/> </center></td>
</tr>

<tr>
<th><center><label>Level 3 </label></center></th>
<td><center> <input type="text" name="person3" id="id_person3" value="{{ EscMat.person3 }}"/> </center></td>
</tr>

<tr>
<th><center><label>Level 4 </label></center></th>
<td><center> <input type="text" name="person4" id="id_person4" value="{{ EscMat.person4 }}"/> </center></td>
</tr>

</table>
<center>
	<button type="submit" class="btn btn-danger">Update</button>
	
</center>
</div>
</form>
{% else %}
 	<center><br/></br>
 	<div style="border:1px solid pink;padding:20px;font-size:20px">
	<h1>Hello Engineer !!!</h1>
	<h2>I am <b><i>SAM</i></b>. <br/>Your Personal Search Engine...!</h2>
	<h3>I store all the documents and details that are required for you!!!<br/>You can login and search for required details!!!</h3>
	<h5>If you are new engineer, Kindly raise to Admin for registering your Login details.</h5></div>
	<!--<a href="{% url 'login' %}" class="btn btn-danger">Login</a></label> -->
</center>
{% endif %}
 
{% endblock content %}	

search/templates/search/editsop.html
{% extends "search/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<center>
<div style="border:1px solid pink;padding:20px;font-size:20px">
<h3>Edit SOP Details</h3>

<form method="POST" class="post-form" action="/updatesop/{{sop.id}}" enctype="multipart/form-data">
	{% csrf_token %}

<table class="table table-striped table-bordered table-sm ">

<tr>
<th><center><label>SOP # </label></center></th>
<td><center> <input type="text" name="doc" id="id_doc" value="{{ sop.doc }}"/> </center></td>
</tr>

<tr>
<th><center><label>Region </label></center></th>
<td><center><select name="region">
<option selected disabled=true>Select Region</option>
<option value="India">India</option>
<option value="Asia">Asia</option>
<option value="Africa">Africa</option>
<option value="mea">MEA</option>
<option value="latam">LATAM</option>
<option value="europe">Europe</option>
<option value="nam">NAM</option>
<option value="Common">Common</option>
</select></center></td>
</tr>

<tr>
<th><center><label>Operator </label></center></th>
<td><center> <input type="text" name="operator" id="id_operator" value="{{ sop.operator }}"/> </center></td>
</tr>

<tr>
<th><center><label for="appt">App or Infra </label></center></th>
<td><center><select name="appt">
<option selected disabled=true>App or Infra</option>
<option value="APP">APP</option>
<option value="INFRA">INFRA</option>
</select> </center></td>
</tr>

<tr>
<th><center><label>Application </label></center></th>
<td><center> <input type="text" name="apname" id="id_apname" value="{{ sop.apname }}"/> </center></td>
</tr>

<tr>
<th><center><label>Topic </label></center></th>
<td><center> <input type="text" name="topic" id="id_topic" value="{{ sop.topic }}"/> </center></td>
</tr>

<tr>
<th><center><label>IP </label></center></th>
<td><center> <input type="text" name="ip" id="id_ip" value="{{ sop.ip }}"/> </center></td>
</tr>

<tr>
<th><center><label>Document </label></center></th>
<td><center> <input type="file" name="pdf" id="id_pdf" value="{{ sop.pdf }}"/> {{ sop.pdf }}</center></td>
</tr>

</table>
<center>
	<button type="submit" class="btn btn-danger">Update</button>
	
</center>
</div>
</form>
{% else %}
 	<center><br/></br>
 	<div style="border:1px solid pink;padding:20px;font-size:20px">
	<h1>Hello Engineer !!!</h1>
	<h2>I am <b><i>SAM</i></b>. <br/>Your Personal Search Engine...!</h2>
	<h3>I store all the documents and details that are required for you!!!<br/>You can login and search for required details!!!</h3>
	<h5>If you are new engineer, Kindly raise to Admin for registering your Login details.</h5></div>
	<!--<a href="{% url 'login' %}" class="btn btn-danger">Login</a></label> -->
</center>
{% endif %}
 
{% endblock content %}	